package eu.trentorise.game.model
import eu.trentorise.game.notification.BadgeNotification;
import eu.trentorise.game.core.Utility;
import java.util.Map
import java.util.ArrayList
import java.util.List;

declare AlreadyLevelUp
end

rule "buyPowerUp"
//The power ups are saved in another database so there I only modify the points
when 
  Action(id=="BuyPowerUp")
  InputData(
    $solution:data['solution'];
  )
  $GoldCoinsScore : PointConcept(name == "GoldCoins")
  $customData : CustomData(this["level"] >=0)
  not AlreadyLevelUp()
then 
  Map solutionMap = ((Map)$solution);
  String priceString = ((String)solutionMap.get("price"));

  Integer price = Integer.parseInt(priceString);

  Integer moneySpent = Integer.parseInt(priceString);
  modify($GoldCoinsScore){setScore($GoldCoinsScore.getScore() - moneySpent);}

  insert(new AlreadyLevelUp());
end